AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda function stack

Parameters:
  S3Bucket:
    Type: String
    Description: S3 bucket for Lambda code
  LambdaRoleArn:
    Type: String
    Description: Lambda execution role ARN
  DeploymentTimestamp:
    Type: String
    Description: Timestamp to force updates
    Default: "1"
  S3Key:
    Type: String
    Description: S3 key for Lambda code
    Default: "lambda.zip"

Resources:
  MyEnterpriseLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: MyEnterpriseLambda
      Handler: lambda_function.lambda_handler
      Role: !Ref LambdaRoleArn
      Runtime: python3.11
      Code:
        S3Bucket: !Ref S3Bucket
        S3Key: !Ref S3Key
      Environment:
        Variables:
          DEPLOYMENT_TIMESTAMP: !Ref DeploymentTimestamp

  WorkdayAPILambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: WorkdayAPILambda
      Handler: workday_api.lambda_handler
      Role: !Ref LambdaRoleArn
      Runtime: python3.11
      Code:
        S3Bucket: !Ref S3Bucket
        S3Key: !Ref S3Key
      Environment:
        Variables:
          DEPLOYMENT_TIMESTAMP: !Ref DeploymentTimestamp
          WORKDAY_API_ENABLED: "true"
      Timeout: 30
      MemorySize: 256 